### ISSUE TITLE
Register file-io as a GHC boot library

### ISSUE THREAD

**Issue by Rufflewind** [haskell/file-io#22]
Can `file-io` be included in the [GHC boot libraries](https://gitlab.haskell.org/ghc/ghc/-/wikis/commentary/libraries/) so that `directory` can depend on it?

This is motivated by https://github.com/haskell/directory/issues/177#issuecomment-2119547309 .

@Bodigrim @bgamari

**Comment by hasufell** [comment]
It can. There's no formal process for it. If a boot package adds a new dependency, then GHC HQ has to include that new depednency when bundling it.

I'd go so far to say this isn't even core lib maintainers business. GHC just chooses to ship with libraries. It's a redistribution effort.

Of course we have to be mindful about e.g. circular dependencies etc.

**Comment by bgamari** [comment]
FWIW, GHC has no objections to adding this dependency as a boot library.

**Comment by Bodigrim** [comment]
Given that Cabal does not like reinstalling boot libraries, we'd better be sure that `file-io` is mature and stable enough. 

One option is to make a release of `directory` which uses `file-io` only if a certain manual Cabal flag is set. This would allow for more testing in the wild to gain more confidence before `file-io` eventually becomes a boot package.

**Comment by hasufell** [comment]
> One option is to make a release of directory which uses file-io only if a certain manual Cabal flag is set.

I'm not sure that gains us much, because that's just directory package using a small part of file-io.

https://github.com/haskell/cabal/issues/9669 needs to be solved, because it is also a security hazard. I can't fix bugs in a timely fashion as a core library maintainer. 

If we were to use a Cabal flag, then:

- it should be True by default (using file-io)
- GHC should disable it when bundling

**Comment by BinderDavid** [comment]
FYI: https://gitlab.haskell.org/hpc/hpc/-/merge_requests/35/diffs#4c23f3e77a0ef00cf8da63e8e50eef5197724f75

I could also provide an `OsPath` compatible API for `hpc` if  `file-io` were a boot library.

**Comment by mpickering** [comment]
@Bodigrim @hasufell @Rufflewind I have opened a GHC issue in order to discuss adding a new boot library (file-io). Please contribute there with your opinions.

https://gitlab.haskell.org/ghc/ghc/-/issues/25145
